### ISSUE TITLE
Firefox Addon

### ISSUE THREAD

**Issue by JadeMaveric** [Bullmeza/BuyNearby#1]
First off, neat extension! You should consider porting it to Firefox and publishing it to their add-on store. Your code seems pretty compliant with the WebExt standard, so it'll require little to no modifications to port.

**Comment by r-muresan** [comment]
Great idea, will do!

**Comment by r-muresan** [comment]
The Firefox addon has been submitted for review; It should be released to the public soon.
Thanks for the support!

**Comment by VictorVow** [comment]
Any update?

**Comment by r-muresan** [comment]
Firefox restricts external scrips. The Google Maps API must be imported externally. I am sorry, there is nothing I can do.

**Comment by VictorVow** [comment]
Manifest V3 in Chrome will do the same thing in disabling use of remotely hosted code. It's a security risk. So you'll need to change the architecture of your extension regardless.
